apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common-api.fullname" . }}
  labels:
    {{- include "common-api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "common-api.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "common-api.fullname" . }}
    spec:
      serviceAccountName: {{ include "common-api.fullname" . }}
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}