apiVersion: v1
kind: Service
metadata:
  name: {{ include "common-api.fullname" . }}
spec:
  selector:
    app: {{ include "common-api.fullname" . }}
  ports:
    - port: {{ .Values.servicePort }}
      targetPort: {{ .Values.containerPort }}