replicaCount: 1

namespaceOverride: ""

image:
  tag: latest

serviceAccount:
  create: true

route:
  enabled: true
  host: ""

build:
  enabled: true
  git:
    uri: "https://github.com/glaceroy/servicemesh-apps.git"
    ref: main
    contextDir: ""
  dockerfilePath: Dockerfile
  sourceSecret: git-secret

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "200m"
    memory: "256Mi"