---
# Allow api-frontend namespace to call into api-external namespace
# Apply this in the api-external namespace
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-frontend-ingress
  namespace: api-external
spec:
  podSelector: {}   # applies to all pods in api-external
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: api-frontend
  policyTypes:
    - Ingress
