kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: api-f1
  namespace: lbg-ocp-servicemesh-3-400-lab
  labels:
    app: api-f1
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'api-f1:latest'
  resources:
    limits:
      cpu: '1'
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/glaceroy/servicemesh-apps.git'
      ref: main
    contextDir: api-f1
    sourceSecret:
      name: git-secret
  triggers:
    - type: ConfigChange
    - type: GitHub
      github:
        secret: git-secret
  runPolicy: Serial
